spring:
  application:
    name: sostitutoincloud
  profiles:
    active: "@spring.profiles.active@"

app:
  storage:
    base-path: /opt/sostitutoincloud/storage
    pdf-path: /opt/sostitutoincloud/storage/pdf
    templates-path: /opt/sostitutoincloud/storage/templates