server:
  port: 8443
  servlet:
    context-path: /sostitutoincloud

app:
  base-url: https://prodpms.siv.cloud.it:8443/sostitutoincloud
  cors:
    allowed-origins: https://prodpms.siv.cloud.it:8443
