# DataSource — prod
#db.url=jdbc:postgresql://prodpms.siv.cloud.it:5432/sostitutoincloud
#db.username=sostitutoincloud
#db.password=CHANGE_ME
#db.driver-class-name=org.postgresql.Driver
#db.pool.maximum-pool-size=20
#db.pool.minimum-idle=5

db.url=${DB_URL:jdbc:postgresql://localhost:5432/sostitutoincloud}
db.username=${DB_USERNAME:sostitutoincloud}
db.password=${DB_PASSWORD:sostitutoincloud}
db.driver-class-name=org.postgresql.Driver
db.pool.maximum-pool-size=20
db.pool.minimum-idle=5
